FROM golang:1.21-alpine AS builder

WORKDIR /app

ADD customer-api/ customer-api/
COPY go.mod ./
COPY go.sum ./
COPY sonar-project.properties ./
COPY Dockerfile.api-golang ./

RUN go build -o customerapi customer-api/cmd/main.go

FROM alpine:3.14

WORKDIR /app

COPY --from=builder /app/customerapi .

ENV POSTGRES_DSN=""
ENV API_PORT=""

# Adicionando usuário não-root
RUN adduser -D -u 1001 appuser
USER appuser

CMD ["./customerapi"]
