// Code generated by mockery v2.36.1. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/fiap-postech-soat1-group21/customer-api/customer-api/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// CustomerUseCase is an autogenerated mock type for the CustomerUseCase type
type CustomerUseCase struct {
	mock.Mock
}

// CreateCustomer provides a mock function with given fields: ctx, c
func (_m *CustomerUseCase) CreateCustomer(ctx context.Context, c *entity.Customer) (*entity.Customer, error) {
	ret := _m.Called(ctx, c)

	var r0 *entity.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Customer) (*entity.Customer, error)); ok {
		return rf(ctx, c)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Customer) *entity.Customer); ok {
		r0 = rf(ctx, c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.Customer) error); ok {
		r1 = rf(ctx, c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RetrieveCustomer provides a mock function with given fields: ctx, c
func (_m *CustomerUseCase) RetrieveCustomer(ctx context.Context, c *entity.Customer) (*entity.Customer, error) {
	ret := _m.Called(ctx, c)

	var r0 *entity.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Customer) (*entity.Customer, error)); ok {
		return rf(ctx, c)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Customer) *entity.Customer); ok {
		r0 = rf(ctx, c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.Customer) error); ok {
		r1 = rf(ctx, c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCustomerUseCase creates a new instance of CustomerUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCustomerUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *CustomerUseCase {
	mock := &CustomerUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
